# Generated by Django 5.2.3 on 2025-06-27 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='electionsettings',
            name='voting_end_time',
            field=models.DateTimeField(blank=True, help_text='Global voting end time for all positions', null=True),
        ),
        migrations.AddField(
            model_name='electionsettings',
            name='voting_start_time',
            field=models.DateTimeField(blank=True, help_text='Global voting start time for all positions', null=True),
        ),
    ]
