# Generated by Django 5.2.3 on 2025-06-28 08:19

import voting.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0002_alter_position_end_time_alter_position_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='photo',
            field=models.ImageField(blank=True, help_text='Profile photo of the candidate (Max 5MB, formats: JPG, PNG, GIF)', null=True, upload_to=voting.models.candidate_photo_path, validators=[voting.models.validate_image_file]),
        ),
    ]
