# Generated by Django 5.2.3 on 2025-06-28 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0003_alter_candidate_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='photo_url',
            field=models.URLField(blank=True, help_text='Cloud storage URL for the candidate photo (automatically set)', null=True),
        ),
    ]
